version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    ports:
      - '3000:3000'
    volumes:
      - .:/srv/app
      - /srv/app/node_modules
    links:
      - mongodb
  mongodb:
    container_name: mongodb-vass
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="vass"
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
  mongodb-test:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="vass-test"
    ports:
      - 27018:27017
    volumes:
      - ./mongo-data-test:/data/db
