version: '3'

services:
  mongodb:
    container_name: mongodb-vass
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="vass"
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
  mongodb-test:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="vass-test"
    ports:
      - 27018:27017
    volumes:
      - ./mongo-data-test:/data/db
