name: API CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['main']

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: node:18
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGODB_DATABASE: ${{ secrets.DB_NAME }}
    env:
      APP_PORT: ${{ secrets.APP_PORT }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm run test:e2e:ci
